### ISSUE TITLE
Browser instructions bugged?

### ISSUE THREAD

**Issue by NullVoxPopuli** [izelnakri/qunitx#74]
Was following:
https://github.com/izelnakri/qunitx#installation-browser

which, at the time of writing is:
```
# Install QUnitX browser runner/cli:
$ npm install -g qunitx-cli
$ qunitx
$ qunitx some-test.js

# with browser output enabled:
$ qunitx some-test.js --debug

```

but this gives the following output:
```
❯ pnpm add qunitx-cli
Packages: +159
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/nullvoxpopuli/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 181, reused 142, downloaded 17, added 159, done

dependencies:
+ qunitx-cli 0.0.3

Done in 3s

❯ pnpm qunitx
./node_modules/.bin/qunitx: 16: exec: TS_NODE_COMPILER_OPTIONS={"module":"ES2020"}: not found

❯ touch some-test.js

❯ pnpm qunitx some-test.js 
./node_modules/.bin/qunitx: 16: exec: TS_NODE_COMPILER_OPTIONS={"module":"ES2020"}: not found

❯ pnpm qunitx some-test.js --debug
./node_modules/.bin/qunitx: 16: exec: TS_NODE_COMPILER_OPTIONS={"module":"ES2020"}: not found

❯ cat package.json 

   1   │ {
   2   │     "dependencies": {
   3   │         "qunitx-cli": "^0.0.3"
   4   │     }
   5   │ }

```

**Comment by izelnakri** [comment]
Hi @NullVoxPopuli , this package has 0 dependency and your issue is related to [qunitx-cli](https://github.com/izelnakri/qunitx-cli/issues) . Thus, I'm closing the issue here, please open it there if it persists.

Which version of node do you use? Also you are executing scripts via `pnpm` it seems. The cli makes no promises of supporting pnpm, but if you'd like to add support, feel free to create a PR on [qunitx-cli](https://github.com/izelnakri/qunitx-cli).

QUnitX-CLI relies on the new loader feature of node.js and uses ts-node package to run ts files.

**Comment by NullVoxPopuli** [comment]
> . The cli makes no promises of supporting pnpm,

should be a non-issue if the deps are configured correctly :p 


> Which version of node do you use?

18.x

> QUnitX-CLI relies on the new loader feature of node.js and uses ts-node package to run ts files.

what node is required? should engines be set to yell at me?
should ts-node be a peerDependency? I feel like I should have had errors related to incorrect dependencies.

**Comment by izelnakri** [comment]
> 18.x

You should use v20.3+ as specified in the engines section of package.json. I dont think more instructions are needed but let me know if we can improve anything.

**Comment by NullVoxPopuli** [comment]
I don't think I got far enough where the engines check was even ran
