### ISSUE TITLE
demo of this working in the browser with node?

### ISSUE THREAD

**Issue by NullVoxPopuli** [izelnakri/qunitx#79]
I tried qunitx a couple times, and haven't been able to get anything to work. Is there a sample repo that demonstrates this working in the browser uning node as the launching environment?

Thanks!

**Comment by izelnakri** [comment]
This issue is (qunitx-cli)[https://github.com/izelnakri/qunitx-cli] related. Yes it works if you use the latest node.js version with support for `---loader` flag, have chromium or chrome browser with `CHROME_BIN` on your path, also you need to have `ts-node` globally installed for it to dynamically resolve the global dependency/transpiler, but currently there is no statically compiled binary distribution for (qunitx-cli)[https://github.com/izelnakri/qunitx-cli].

I'm currently improving the test suite for qunitx-cli, then will see how to distribute it as a statically compiled binary in nixpkgs repository as this is not an easy or commonly done thing especially for TypeScript projects written in node.js yet.

Closing this issue here, let me know if you'd like it to be reopened.

**Comment by NullVoxPopuli** [comment]
> , also you need to have ts-node globally installed for it to dynamically resolve the global dependency/transpiler, 

This is likely my problem, but this is also pretty bad DX, imo -- I do not install global tools, aside from `pnpm`. 
ts-node should be a dependency of the CLI. Otherwise, how could you guarantee that the cli works for all versions of ts-node?

**Comment by izelnakri** [comment]
last time I tried the ts-node dependency could not be reliably  referenced locally even if you include it as a dependency of the package because of the way it runs now, however as I mentioned, `ts-node` might not be needed anymore.
